flowchart TD

INACTIVE -- deal --> WAITING_FOR_INIT_VRF
WAITING_FOR_INIT_VRF -- fulfill --> PLAYER_TURN
WAITING_FOR_INIT_VRF -- fail --> FAILED_VRF
FAILED_VRF -- return_bet --> INACTIVE
PLAYER_TURN -- hit --> WAITING_FOR_PLAYER_VRF

WAITING_FOR_PLAYER_VRF -- fulfill --> RESOLVING_PLAYER_HAND
RESOLVING_PLAYER_HAND -- value>21 --> INACTIVE
RESOLVING_PLAYER_HAND -- value<=21 --> PLAYER_TURN

WAITING_FOR_PLAYER_VRF -- fail --> FAILED_VRF
PLAYER_TURN -- stand --> WAITING_FOR_DEALER_VRF
WAITING_FOR_DEALER_VRF -- fulfill --> RESOLVING_DEALER_HAND
WAITING_FOR_DEALER_VRF -- fail --> FAILED_VRF
RESOLVING_DEALER_HAND --> INACTIVE

// https://mermaid.live/edit#pako:eNp9kvFrgkAYhv8V-X62ME29ZAtk2iaIDXONjQO55bkEPcPObS3636eVa5XzJ8_vnvfz5cEtLPKIggFxmn8ulqTgQmBhhpnjmXeBM7eFXk-IKEmr51h4Np3A8e7DydQPHc8Jwrk_waxtWsfiMo2T9JB8dM0X2w-DJ9_rCJDkQE9Mx7Wtw_bTuUYKysuChW-U78GmJWZ_PlBzy4RfNT4i-63nJU43l719ezZ15zV3ZB5Mr_LTOq6zHyQt6VgeXLTr5m9uj4EzS50V20xdKFhzwqIrCZZtuo2E9vn_Co7MQUFHuK1c65YzSyBCRouMJFH1O24xEwQMfEkzisGojhGNSZlyDJjtKrRcRYRTO0p4XoARk3RNRSAlz2cbtgCDFyVtICsh7wXJfqkVYa95njVQ9QrGFr7A0NQ-koa6Lqs6GskqGomwAWOgo74kIw0hWRkiTR8oOxG-9wukPtI0ZaQoiiopg2F99QNIqPul


